In [3]:
import pandas as pd
import numpy as np

Question1:Version of NumPy*

In [4]:
np.__version__

'1.21.6'

Question2: Number of records in the dataset

In [5]:
pd.read_csv("data.csv")


Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

Question 3: The most popular car manufacturers


In [7]:
df=pd.read_csv("data.csv")

In [21]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [40]:
new_df=df.drop_duplicates('Popularity')


In [ ]:
new_df.nlargest(n=3,columns='Popularity')

In [42]:
print(new_df.head(200))

                Make               Model  Year  \
0                BMW          1 Series M  2011   
17              Audi                 100  1992   
32              FIAT          124 Spider  2017   
35     Mercedes-Benz           190-Class  1991   
64          Chrysler                 200  2015   
87            Nissan               200SX  1996   
104            Volvo                 240  1991   
112            Mazda                   2  2012   
194       Mitsubishi              3000GT  1997   
294          Ferrari                 360  2002   
474       Alfa Romeo                  4C  2015   
479           Toyota             4Runner  2014   
604          McLaren                570S  2016   
611          Maybach                  57  2010   
674          Pontiac                6000  1990   
736          Porsche          718 Cayman  2017   
800             Saab                9-2X  2005   
1137             GMC      Acadia Limited  2017   
1171         Hyundai              Accent  2014   


Question 4: Number of unique Audi car models

In [46]:
df.groupby('Make')['Model'].nunique()

Make
Acura            18
Alfa Romeo        1
Aston Martin     12
Audi             34
BMW              39
Bentley          18
Bugatti           1
Buick            20
Cadillac         30
Chevrolet        63
Chrysler         19
Dodge            33
FIAT              5
Ferrari          14
Ford             51
GMC              30
Genesis           1
HUMMER            2
Honda            21
Hyundai          22
Infiniti         38
Kia              16
Lamborghini       6
Land Rover       11
Lexus            46
Lincoln          16
Lotus             5
Maserati          8
Maybach           3
Mazda            31
McLaren           4
Mercedes-Benz    40
Mitsubishi       22
Nissan           32
Oldsmobile       18
Plymouth         10
Pontiac          20
Porsche          12
Rolls-Royce      10
Saab              8
Scion             8
Spyker            1
Subaru           16
Suzuki           16
Tesla             1
Toyota           39
Volkswagen       31
Volvo            26
Name: Model, dtype: int64

Question 5: Number of columns with missing values


In [52]:
print(df.isnull().any())
'''isnull function is used to find null values .any display column that have atlest 1 null value if i 
want to display rows having null value then i will mention .any(axis=1)'''


Make                 False
Model                False
Year                 False
Engine Fuel Type      True
Engine HP             True
Engine Cylinders      True
Transmission Type    False
Driven_Wheels        False
Number of Doors       True
Market Category       True
Vehicle Size         False
Vehicle Style        False
highway MPG          False
city mpg             False
Popularity           False
MSRP                 False
dtype: bool


'isnull function is used to find null values .any display column that have atlest 1 null value if i \nwant to display rows having null value then i will mention .any(axis=1)'

Question 6:
^Find the median value of "Engine Cylinders" column in the dataset.
^Next, calculate the most frequent value of the same "Engine Cylinders".
^Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
^Now, calculate the median value of "Engine Cylinders" once again.
^Has it changed?

In [8]:
df['Engine Cylinders'].median()

6.0

In [9]:
df['Engine Cylinders'].mode()

0    4.0
dtype: float64

In [13]:
df['Engine Cylinders'].fillna(4.0)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [14]:
df['Engine Cylinders'].median()

6.0

Question 7
^Select all the "Lotus" cars from the dataset.
^Select only columns "Engine HP", "Engine Cylinders".
^Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
^Get the underlying NumPy array. Let's call it X.
^Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result   XTX.
^Invert XTX.
^Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
^Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
^What's the value of the first element of w?

In [17]:
df_lotus=df.loc[df['Make']=='Lotus']

In [32]:
a=df_lotus[['Engine HP', 'Engine Cylinders']]

In [33]:
a.drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [34]:
new=a.drop_duplicates()

In [35]:
new.to_numpy()

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [36]:
x=new.to_numpy()

In [37]:
np.transpose(x)

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [42]:
xt=np.transpose(x)#transpose of x(np array)

In [48]:
np.matmul(xt,x)

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [49]:
xtx=np.matmul(xt,x)

In [52]:
np.linalg.inv(xtx)

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [54]:
inverse=np.linalg.inv(xtx)

In [53]:
y=[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [61]:
transpose_xtx=np.transpose(xtx)
np.matmul(inverse,xt)

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [63]:
mul=np.matmul(inverse,xt)
w=np.matmul(mul,y)

In [64]:
w

array([  4.59494481, -63.56432501])